### ISSUE TITLE
Sound effects still playing at random when muted

### ISSUE THREAD

**Issue by gbaudic** [quaap/SeafoodBerserker#6]
Even with the volume slider for sound effects set at the minimum value in Preferences, sound effects are still played sometimes when playing the game. I have not been able to notice a pattern here, this seems to happen randomly. 
This problem only affects the sound effects, the music is fine.

**Comment by quaap** [comment]
I've not noticed it, but I see a way in the code it could be happening.  I'll try to push a potential fix for this in the next update.  Thanks for reporting!
